// SPDX-License-Identifier: MIT
// GENERATED by scripts/gen-codes.mjs from spec/codes.json - DO NOT EDIT.
// Drift-locked by test/codes-registry.test.ts. Regenerate with: npm run gen:codes
/* eslint-disable */

/** One entry in the openOM finding-code registry. */
export interface CodeEntry {
  readonly message: string;
  readonly requirement: string;
  readonly severity: "error" | "warning" | "info";
}

/** The canonical finding-code registry (code → message + requirement + severity), from spec/codes.json. */
export const OM_CODES: Readonly<Record<string, CodeEntry>> = Object.freeze({
  "OMI-I001": {
    "message": "currency member absent; the payload is interpreted as USD",
    "requirement": "OM-DD-002",
    "severity": "info"
  },
  "OMI-I002": {
    "message": "rentPeriod source omitted; provenance defaults to 'asserted'",
    "requirement": "OM-DD-004",
    "severity": "info"
  },
  "OMI-I003": {
    "message": "advisory context for a skipped or non-applicable consistency check",
    "requirement": "OM-ERR-014",
    "severity": "info"
  },
  "OMV-E001": {
    "message": "payload does not conform to the openOM 0.1 JSON Schema",
    "requirement": "OM-DD-001",
    "severity": "error"
  },
  "OMV-E002": {
    "message": "noiType and noiAsOfDate are required when deal.noi is present",
    "requirement": "OM-DD-003",
    "severity": "error"
  },
  "OMV-E003": {
    "message": "meta.signature is neither null nor the reserved {alg,keyId,value} shape",
    "requirement": "OM-ERR-090",
    "severity": "error"
  },
  "OMV-E010": {
    "message": "meta.supersedes is not a 'sha256:'<64-hex> string or null",
    "requirement": "OM-ERR-013",
    "severity": "error"
  },
  "OMV-E011": {
    "message": "integer value exceeds the ECMAScript safe range (2^53-1); embed would reject it",
    "requirement": "OM-CANON-013",
    "severity": "error"
  },
  "OMW-W010": {
    "message": "capRate disagrees with noi / askingPrice beyond tolerance",
    "requirement": "OM-CONS-010",
    "severity": "warning"
  },
  "OMW-W011": {
    "message": "pricePerSF disagrees with askingPrice / buildingSF beyond tolerance",
    "requirement": "OM-CONS-011",
    "severity": "warning"
  },
  "OMW-W012": {
    "message": "pro-forma NOI given without a noiAsOfDate",
    "requirement": "OM-CONS-012",
    "severity": "warning"
  },
  "OMW-W013": {
    "message": "capRate falls outside the plausibility band",
    "requirement": "OM-CONS-013",
    "severity": "warning"
  },
  "OMW-W014": {
    "message": "a monetary or area value is present but non-positive",
    "requirement": "OM-CONS-014",
    "severity": "warning"
  },
  "OMW-W020": {
    "message": "year-1 scheduled rent disagrees with the stated in-place NOI",
    "requirement": "OM-CONS-020",
    "severity": "warning"
  },
  "OMW-W021": {
    "message": "a gap exists between consecutive rent-schedule periods",
    "requirement": "OM-CONS-021",
    "severity": "warning"
  },
  "OMW-W022": {
    "message": "rent-schedule periods overlap in time",
    "requirement": "OM-CONS-022",
    "severity": "warning"
  },
  "OMW-W023": {
    "message": "escalationFromPrior disagrees with the actual rent step",
    "requirement": "OM-CONS-023",
    "severity": "warning"
  },
  "OMW-W024": {
    "message": "rentPSF disagrees with annualRent / SF",
    "requirement": "OM-CONS-024",
    "severity": "warning"
  },
  "OMW-W025": {
    "message": "monthlyRent disagrees with annualRent / 12",
    "requirement": "OM-CONS-025",
    "severity": "warning"
  },
  "OMW-W026": {
    "message": "a rent period falls outside the lease term",
    "requirement": "OM-CONS-026",
    "severity": "warning"
  },
  "OMW-W030": {
    "message": "remaining lease term disagrees with the term dates",
    "requirement": "OM-CONS-030",
    "severity": "warning"
  },
  "OMW-W031": {
    "message": "total lease term disagrees with the term dates",
    "requirement": "OM-CONS-031",
    "severity": "warning"
  },
  "OMW-W032": {
    "message": "assertedDate is in the future relative to the processing date",
    "requirement": "OM-CONS-032",
    "severity": "warning"
  },
  "OMW-W033": {
    "message": "noiAsOfDate is later than assertedDate",
    "requirement": "OM-CONS-033",
    "severity": "warning"
  },
  "OMW-W034": {
    "message": "lease expiration is on or before its commencement",
    "requirement": "OM-CONS-034",
    "severity": "warning"
  },
  "OMW-W040": {
    "message": "a net-lease type is stated but pass-throughs are missing/inconsistent",
    "requirement": "OM-CONS-040",
    "severity": "warning"
  },
  "OMW-W041": {
    "message": "stated lease type disagrees with the expense responsibilities",
    "requirement": "OM-CONS-041",
    "severity": "warning"
  },
  "OMW-W050": {
    "message": "meta.supersedes equals this payload's own hash (self-supersede no-op)",
    "requirement": "OM-CONS-050",
    "severity": "warning"
  },
  "OMW-W060": {
    "message": "a source claims 'verified' that the tooling cannot verify",
    "requirement": "OM-CONS-060",
    "severity": "warning"
  },
  "OMW-W061": {
    "message": "currency absent; USD assumed (paired with OMI-I001)",
    "requirement": "OM-DD-002",
    "severity": "warning"
  },
  "OMW-W062": {
    "message": "addressRegion is not a US state - use the 2-letter code (e.g. MI)",
    "requirement": "OM-CONS-062",
    "severity": "warning"
  },
  "OMW-W063": {
    "message": "addressLocality looks like a state, not a city - check the mapping",
    "requirement": "OM-CONS-063",
    "severity": "warning"
  },
  "OMW-W064": {
    "message": "streetAddress appears to include the city/state/ZIP - put only the street line",
    "requirement": "OM-CONS-064",
    "severity": "warning"
  },
  "OMW-W051": {
    "message": "a same-domain mirror carries a newer, superseding assertion (stale)",
    "requirement": "OM-TRUST-009",
    "severity": "warning"
  },
  "OMW-W052": {
    "message": "a same-domain mirror shows different, non-superseding content (diverged)",
    "requirement": "OM-TRUST-010",
    "severity": "warning"
  }
});

/** Every validation/consistency/info code the validator can emit - a stable, enumerable API. */
export type OmCode =
  | "OMI-I001"
  | "OMI-I002"
  | "OMI-I003"
  | "OMV-E001"
  | "OMV-E002"
  | "OMV-E003"
  | "OMV-E010"
  | "OMV-E011"
  | "OMW-W010"
  | "OMW-W011"
  | "OMW-W012"
  | "OMW-W013"
  | "OMW-W014"
  | "OMW-W020"
  | "OMW-W021"
  | "OMW-W022"
  | "OMW-W023"
  | "OMW-W024"
  | "OMW-W025"
  | "OMW-W026"
  | "OMW-W030"
  | "OMW-W031"
  | "OMW-W032"
  | "OMW-W033"
  | "OMW-W034"
  | "OMW-W040"
  | "OMW-W041"
  | "OMW-W050"
  | "OMW-W060"
  | "OMW-W061"
  | "OMW-W062"
  | "OMW-W063"
  | "OMW-W064"
  | "OMW-W051"
  | "OMW-W052";
