// SPDX-License-Identifier: MIT
// GENERATED by scripts/gen-types.mjs from spec/om-0.1.schema.json — DO NOT EDIT.
// Drift-locked by test/payload-types.test.ts. Regenerate with: npm run gen:types
/* eslint-disable */

export type Sha256OrNull = null | string;

/**
 * An openOM payload is an ADVERTISEMENT - the broker's opinion of value, agreed to by the seller before publication; it records who asserted it, unaltered, and as of when, and never claims the opinion is true (verified = provenance, not truth). JSON Schema (2020-12) for the openOM 0.1 offering-memorandum payload. Human-readable mirror is spec Part II §E; on conflict the spec wins. Forward-compatible: unknown OPTIONAL members are permitted ([OM-VER-003]). The unprefixed top-level key space is RESERVED for the standard; non-standard/vendor fields belong under the `ext` object (#115) so they cannot collide with future core terms. CONFORMANCE NOTE: date/uri `format` keywords are ASSERTED, not annotation-only — an implementation MUST enable full format assertion (ajv-formats mode:full / Python jsonschema Draft202012Validator with a FormatChecker) to reproduce the published conformance outcomes ([OM-VAL-002]).
 */
export interface OpenOMPayload01 {
  /**
   * schema.org + the openOM namespace https://openom.app/ns/0.1 (vocabulary published at spec/context/openom-0.1.jsonld).
   *
   * @minItems 1
   */
  "@context": [string, ...string[]];
  "@type": "RealEstateListing";
  specVersion: "0.1";
  /**
   * ISO 4217; default USD when absent ([OM-DD-002]).
   */
  currency?: string;
  assertedBy: {
    broker: string;
    brokerage: string;
    license: string;
    /**
     * OPTIONAL (#118). The asserting party's website - the identity anchor §10 layer-3 origin verification binds to. Reserved for the registry-era license↔domain↔key cross-check.
     */
    website?: string;
    /**
     * OPTIONAL (#118). ISO 3166-1/-2 code (e.g. US, US-CA) disambiguating the license number's authority space for worldwide use.
     */
    licenseJurisdiction?: string;
    /**
     * OPTIONAL (#118). Name of the issuing licensing authority.
     */
    licenseAuthority?: string;
    [k: string]: unknown;
  };
  assertedDate: string;
  property?: {
    /**
     * OPTIONAL (#114). Extensible discriminator: retail | office | industrial | multifamily | land | mixed-use | hospitality | self-storage | other. Open string in 0.1; 0.2 may formalize the enum.
     */
    propertyType?: string;
    address?: {
      streetAddress?: string;
      addressLocality?: string;
      addressRegion?: string;
      postalCode?: string;
      addressCountry?: string;
      [k: string]: unknown;
    };
    geo?: {
      latitude?: number;
      longitude?: number;
      [k: string]: unknown;
    };
    apn?: string;
    buildingSF?: number;
    lotAcres?: number;
    yearBuilt?: number;
    yearRenovated?: number;
    /**
     * OPTIONAL. Total rentable units (multifamily / mixed-use).
     */
    units?: number;
    /**
     * OPTIONAL. Occupancy as a decimal fraction (0.95 = 95%), matching the capRate fraction convention.
     */
    occupancy?: number;
    [k: string]: unknown;
  };
  deal?: {
    askingPrice?: number;
    capRate?: number;
    noi?: number;
    noiType?: "in-place" | "pro-forma";
    noiAsOfDate?: string;
    pricePerSF?: number;
    /**
     * OPTIONAL. Asking price per unit (multifamily analog of pricePerSF).
     */
    pricePerUnit?: number;
    status?: "active" | "under-contract" | "sold" | "withdrawn";
    [k: string]: unknown;
  };
  lease?: {
    tenantEntity?: string;
    guarantor?: {
      name?: string;
      type?: "corporate" | "franchisee" | "personal" | "none";
      [k: string]: unknown;
    };
    landlordResponsibilities?: {
      roof?: boolean;
      structure?: boolean;
      parking?: boolean;
      hvac?: boolean;
      taxes?: boolean;
      insurance?: boolean;
      cam?: boolean;
      [k: string]: unknown;
    };
    leaseTypeAsserted?: "N" | "NN" | "NNN" | "absolute-net" | "gross" | "modified-gross";
    commencement?: string;
    expiration?: string;
    /**
     * Stated total lease term in months; cross-checked against expiration - commencement (OMW-W031).
     */
    termMonths?: number;
    /**
     * Stated remaining term in months as of assertedDate; cross-checked against expiration - as_of (OMW-W030).
     */
    remainingTermMonths?: number;
    rentSchedule?: RentPeriod[];
    options?: {
      count?: number;
      lengthYears?: number;
      escalation?: string;
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
  meta: {
    sourceDocHash?: Sha256OrNull;
    supersedes: Sha256OrNull;
    /**
     * Reserved (#117, §11.1 layer-4). Either null/absent OR the {alg,keyId,value} envelope. 0.1 consumers MUST IGNORE a populated value (no trust weight); it is excluded from the integrity preimage ([OM-CANON-003]) so it stays additive. A value that is neither null nor the reserved shape is OMV-E003.
     */
    signature?: null | {
      alg: string;
      keyId: string;
      value: string;
      [k: string]: unknown;
    };
    imageRights?: string;
    /**
     * OPTIONAL ([M1]). The canonical HTTPS URL where this exact payload is mirrored as JSON-LD on the web, on the SAME registrable domain as assertedBy.website. A consumer auto-derives the origin-verification mirror from it (no per-listing config), reaching the domain-origin (✓✓) and staleness states. The mirror MUST serve the exact JCS payload bytes (its byte-hash equals payloadHash). Same-domain enforced at verify time; a cross-domain value simply does not verify.
     */
    canonicalUrl?: string;
    [k: string]: unknown;
  };
  /**
   * OPTIONAL (#115). The ONLY place non-standard/vendor fields belong - namespaced by vendor (e.g. `"ext": { "acme": { ... } }`) so they never collide with future core terms. 0.1 tools preserve it and MUST NOT interpret it.
   */
  ext?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface RentPeriod {
  periodStart: string;
  periodEnd: string;
  annualRent: number;
  monthlyRent?: number;
  rentPSF?: number;
  escalationFromPrior?: number;
  abatement?: null | number;
  /**
   * Per-field provenance ([OM-DD-004]). In 0.1 `source` is carried ONLY here on rentPeriod objects; scalar-field and options[] provenance is deferred to a future provenance-side-map minor (#44). Absent → assume `asserted`.
   */
  source?: "asserted" | "extracted" | "verified";
  [k: string]: unknown;
}

/** The openOM payload — the central data contract. Alias of the schema's root type. */
export type OMPayload = OpenOMPayload01;
/** JSON-LD @type of an openOM payload. */
export type RealEstateListing = OMPayload;
