// Generate the finding-code registry + OmCode union from spec/codes.json.
//
// [Mi19] Codes are a stable API but were typed as bare `string`, and codes.json was not shipped in
// the npm package. This emits a committed src/codes.ts (drift-locked by test/codes-registry.test.ts)
// exporting OM_CODES (code -> {message, requirement, severity}) and an `OmCode` string-literal union,
// so a consumer gets autocomplete + exhaustiveness on Finding.code and can enumerate the registry.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const codes = JSON.parse(readFileSync(resolve(here, "../../spec/codes.json"), "utf8")).codes;
const outPath = resolve(here, "../src/codes.ts");

const entries = Object.entries(codes); // preserves spec order
const union = entries.map(([c]) => `  | ${JSON.stringify(c)}`).join("\n");
const body = JSON.stringify(codes, null, 2);

const out = `// SPDX-License-Identifier: MIT
// GENERATED by scripts/gen-codes.mjs from spec/codes.json — DO NOT EDIT.
// Drift-locked by test/codes-registry.test.ts. Regenerate with: npm run gen:codes
/* eslint-disable */

/** One entry in the openOM finding-code registry. */
export interface CodeEntry {
  readonly message: string;
  readonly requirement: string;
  readonly severity: "error" | "warning" | "info";
}

/** The canonical finding-code registry (code → message + requirement + severity), from spec/codes.json. */
export const OM_CODES: Readonly<Record<string, CodeEntry>> = Object.freeze(${body});

/** Every validation/consistency/info code the validator can emit — a stable, enumerable API. */
export type OmCode =
${union};
`;

writeFileSync(outPath, out);
console.log(`gen-codes: wrote src/codes.ts (${entries.length} codes)`);
