// Generate the OMPayload TypeScript type from spec/om-0.1.schema.json.
//
// [Ma3] The payload is the central data contract, but every API used Record<string, unknown>, so a
// TS integrator got zero compile-time help on field names / noiType enum / date formats / nesting.
// This emits an authoritative `OMPayload` (aliased RealEstateListing) + nested interfaces from the
// single-source schema, committed and drift-locked by test/payload-types.test.ts. Regenerate with:
//   npm run gen:types
import { compileFromFile } from "json-schema-to-typescript";
import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const specPath = resolve(here, "../../spec/om-0.1.schema.json");
const outPath = resolve(here, "../src/payload-types.ts");

const ts = await compileFromFile(specPath, {
  bannerComment: `// SPDX-License-Identifier: MIT
// GENERATED by scripts/gen-types.mjs from spec/om-0.1.schema.json — DO NOT EDIT.
// Drift-locked by test/payload-types.test.ts. Regenerate with: npm run gen:types
/* eslint-disable */`,
  additionalProperties: true, // the payload is forward-compatible ([OM-VER-003]); allow unknown members
  style: { singleQuote: false, semi: true },
  cwd: dirname(specPath),
});

// The root interface is named from the schema title ("openOM payload 0.1"); expose stable aliases.
const withAliases =
  ts +
  `
/** The openOM payload — the central data contract. Alias of the schema's root type. */
export type OMPayload = OpenOMPayload01;
/** JSON-LD @type of an openOM payload. */
export type RealEstateListing = OMPayload;
`;

writeFileSync(outPath, withAliases);
console.log(`gen-types: wrote src/payload-types.ts (${withAliases.length} bytes)`);
