// Bundle spec/om-0.1.schema.json into the npm package as a JS module constant.
//
// [Bl1] The published npm package cannot rely on the repo's /spec directory (not packed) nor on a
// JSON subpath import (blocked by the `exports` map + non-portable across Node/browser/Workers). The
// portable, tree-shakeable answer is a generated TS const, mirroring how core/schema.py ships the
// schema as package data. Drift-locked by test/schema.test.ts (OM_SCHEMA deep-equals the spec file).
//
// Run at build (prebuild) and committed so `git`-clone + `tsc` works. SPEC_VERSION is derived from
// the schema's own $id so it can never disagree with the shipped schema.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const specPath = resolve(here, "../../spec/om-0.1.schema.json");
const outPath = resolve(here, "../src/schema.ts");

const raw = readFileSync(specPath, "utf8");
const schema = JSON.parse(raw);

const idMatch = /om-(\d+\.\d+)\.schema\.json/.exec(String(schema.$id ?? ""));
if (!idMatch) throw new Error(`gen-schema: cannot derive SPEC_VERSION from $id: ${schema.$id}`);
const specVersion = idMatch[1];

// Re-serialize (2-space) from the parsed object so the emitted literal is normalized JSON, not a
// pasted string. schema.ts is prettier/eslint-ignored (generated); the test guards the VALUE.
const literal = JSON.stringify(schema, null, 2);

const out = `// SPDX-License-Identifier: MIT
// GENERATED by scripts/gen-schema.mjs from spec/om-0.1.schema.json - DO NOT EDIT.
// Drift-locked by test/schema.test.ts. Regenerate with: npm run gen:schema
/* eslint-disable */

/** The openOM ${specVersion} payload version, derived from the bundled schema's \`$id\`. */
export const SPEC_VERSION = ${JSON.stringify(specVersion)};

/**
 * The openOM ${specVersion} payload JSON Schema (2020-12), bundled so \`validatePayload(payload)\`
 * runs from a fresh install with no repo clone. Byte-equal in value to spec/om-0.1.schema.json.
 */
export const OM_SCHEMA: Record<string, unknown> = Object.freeze(${literal}) as Record<
  string,
  unknown
>;

/** The bundled schema as a cached object (identity-stable, mirrors core.schema.load_schema). */
export function loadSchema(): Record<string, unknown> {
  return OM_SCHEMA;
}
`;

writeFileSync(outPath, out);
console.log(`gen-schema: wrote src/schema.ts (SPEC_VERSION=${specVersion}, ${out.length} bytes)`);
