"""#129: JCS differential-fuzz corpus. Canonicalize 600 edge-weighted objects and assert each hash
matches the committed `expected` (regenerated by gen_fuzz_corpus.py). This is the Python half of the
cross-language check: fuzz.test.ts runs the SAME corpus + expected in the TS core, so any byte-level
divergence between the two RFC 8785 impls fails one of the two - the silent-fork guard the project
fears. Deterministic + offline."""

from __future__ import annotations

import json
from pathlib import Path

from openom_core.canonical import canonicalize, hash_bytes

FUZZ = Path(__file__).resolve().parents[2] / "spec" / "vectors" / "fuzz"


def _lines(name: str) -> list[str]:
    return FUZZ.joinpath(name).read_text(encoding="utf-8").splitlines()


def test_fuzz_corpus_hashes_match_expected() -> None:
    corpus = _lines("corpus.jsonl")
    expected = _lines("expected.jsonl")
    assert len(corpus) == len(expected) >= 500, "corpus/expected length mismatch or too small"
    for i, (line, want) in enumerate(zip(corpus, expected, strict=True)):
        got = hash_bytes(canonicalize(json.loads(line)))
        assert got == want, f"vector {i}: {got} != {want}\n  input: {line}"
